### ISSUE TITLE
Deployment failure? // Create_Flow_XML_File // RetrieveFlow.extractedMetadataString

### ISSUE THREAD

**Issue by juhalassila** [ericrsmith35/Import-Export-Flows#1]
Hi! I'm trying to do a fresh install to a sandbox.

Before this attempt I installed FlowActionBasePack, FlowScreenComponentsBasePack and FlowPicker

Here's what I get:

...
Deployment Complete
Failures:
deploy/flows/Import_Export_Flows.flow(Import_Export_Flows):Create_Flow_XML_File (Action) - The element has an invalid reference to "RetrieveFlow.extractedMetadataString".
flows/Import_Export_Flows.flow
package.xml
classes/RetrieveFileTest.cls-meta.xml
classes/CreateFileTest.cls-meta.xml
classes/CreateFile.cls-meta.xml
classes/RetrieveFile.cls-meta.xml
classes/RetrieveFile.cls
classes/CreateFile.cls
classes/CreateFileTest.cls
classes/RetrieveFileTest.cls

pic:
![image](https://user-images.githubusercontent.com/26527282/97774629-38493980-1b62-11eb-80c9-c1af74ae6d19.png)

**Comment by juhalassila** [comment]
It looks like I managed to deploy successfully after upgrading FlowBaseComponents.
Somehow I was thinking that after installing BasePacks, FlowBaseComponents would not be needed which seems not to be the case. ( https://unofficialsf.com/introducing-flowbasecomponents/ )

**Comment by ericrsmith35** [comment]
Glad you got it working.  I have not refactored this component to use the newer
